# Name of your application. Used to uniquely configure containers.
service: rubycats

# Name of the container image.
image: rubycats-com/rubycats

# Deploy to these servers.
servers:
  web:
    hosts:
      - rubycats.com
    options:
      "add-host": host.docker.internal:host-gateway

# Credentials for your image host.
registry:
  server: ghcr.io
  username: ineedjet
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .env).
# Remember to run `kamal env push` after making changes!
env:
 clear:
   SITE_NAME: RubyCats
   SITE_URL: https://rubycats.com
   DB_HOST: host.docker.internal
   DB_PORT: 5432
   DB_NAME: rubycats-com
   DB_USER: rubycats-com
 secret:
   - RAILS_MASTER_KEY
   - DB_PASSWORD

# Use a different ssh user than root
ssh:
  user: rubycats-com

# Configure builder setup.
# builder:
#   args:
#     RUBY_VERSION: 3.2.2
#   secrets:
#     - GITHUB_TOKEN
#   remote:
#     arch: amd64
#     host: ssh://app@192.168.0.1

# Use accessory services (secrets come from .env).
# accessories:
#   db:
#     image: mysql:8.0
#     host: 192.168.0.2
#     port: 3306
#     env:
#       clear:
#         MYSQL_ROOT_HOST: '%'
#       secret:
#         - MYSQL_ROOT_PASSWORD
#     files:
#       - config/mysql/production.cnf:/etc/mysql/my.cnf
#       - db/production.sql:/docker-entrypoint-initdb.d/setup.sql
#     directories:
#       - data:/var/lib/mysql
#   redis:
#     image: redis:7.0
#     host: 192.168.0.2
#     port: 6379
#     directories:
#       - data:/data

# Configure custom arguments for Traefik
traefik:
  host_port: 127.0.0.1:8091
