name: Code quality
on:
  - push
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '3.2.2' ]
    env:
      ImageOS: ubuntu20
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}
      - name: Check standardrb
        run: bundle exec standardrb --format progress
  bundle-audit:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '3.2.2' ]
    env:
      ImageOS: ubuntu20
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}
      - name: Check bundle audit
        run: bundle exec bundle-audit check --update
  specs:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '3.2.2' ]
    env:
      ImageOS: ubuntu22
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}
      - name: Install PostgreSQL client
        run: |
          sudo apt-get -yqq install libpq-dev
      - name: Setup DB, Run tests
        env:
          GITHUB_ACTIONS: true
          SERVICE_NAME: test
          DEPLOY_ENV: ""
          PORT: "3000"
          BASE_URL: http://localhost:3000
          BASE_API_URL: http://localhost:3000
          RACK_ENV: test
          DATABASE_URL: postgres://postgres:password@localhost/ins_test?max_connections=5
        run: |
          bundle exec rake db:create db:migrate
          bundle exec rspec --format progress
      
